### PR TITLE
Add instructions for setting the app icon

### PR DESCRIPTION
**Pull request by thenaterhood**
Just to get this out of the way since it's quick.

This needs to be vetted on iOS before being approved.

### CODE REVIEW

**Comment by bbesmanoff** [comment]
Does not appear to work on iOS as posted in the setup (at least using the provided XML snippet)

**Comment by CShapleigh** [comment]
This works for me in Android....unfortunately cannot test iOS :(

**Comment by thenaterhood** [comment]
@bbesmanoff Try adding this line to your config.xml. It doesn't go in the <platform...> blocks as it should set a default icon for all platforms.

```
<icon src="../resources/icons/Icon@2x.png" />
```

If that works, I'll update the instructions here. It appears to work fine on Android.

**Comment by thenaterhood** [comment]
I went ahead and pushed the updated instructions since they should get reviewed anyway. I suspect it'll work on iOS without a problem doing it that way.

**Comment by bbesmanoff** [comment]
The new method works on iOS

:+1:

**Comment by thenaterhood** [comment]
@CShapleigh I've changed the instructions slightly since you last looked at this if you want to poke it again.

**Comment by CShapleigh** [comment]
eyyy :+1:

**Pull request merged**
