### PR TITLE
Move the resources directory to a submodule

### PR DESCRIPTION
**Pull request by thenaterhood**
This pull removes the resources directory contents and pulls them from the https://github.com/tourtrak/resources repository as a submodule. This does **not** change the setup process for the app from the instructions perspective, as pulling in the submodule is already handled by one of the steps.

### CODE REVIEW

**Comment by CShapleigh** [comment]
If it works, it works :+1:

**Comment by thenaterhood** [comment]
It worked on my end. I honestly have no idea why it wouldn't once you've pulled the submodule in but it'd be worth checking it again.

**Comment by cman131** [comment]
This looks fine to me. Why do you feel it may not work?

**Comment by thenaterhood** [comment]
I don't think it won't work, I just wanted confirmation that it works from someone on another system since this changes how we handle some 7,000 files.

**Comment by CShapleigh** [comment]
so it works for me

**Comment by CShapleigh** [comment]
hell nice

**Comment by bbesmanoff** [comment]
:beer:

**Pull request merged**
