### PR TITLE
Remove setting color per usermarker

### PR DESCRIPTION
**Pull request by bbesmanoff**
It appears that this functionality is missing in the current version of
Leaflet.  This also caused a problem in a previous change where the
current user wasn't being displayed on map for the same reason.  It may
be possible to look into alternatives in the future

### CODE REVIEW

**Comment by thenaterhood** [comment]
There's a couple other references to color that could get removed with this as well, if we choose to go through with it.

**Comment by CShapleigh** [comment]
:+1:

**Comment by cman131** [comment]
:european_post_office: I'm good with it :+1:

**Comment by CShapleigh** [comment]
this pull is deprecated, should be closed @bbesmanoff

**Pull request closed without merging**
